/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as ApiGuruChatRouteImport } from './routes/api/guru.chat'
import { Route as ApiAuthTelegramRouteImport } from './routes/api/auth.telegram'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicPracticeSendRemindersRouteImport } from './routes/api/public/practice/send-reminders'

const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuruChatRoute = ApiGuruChatRouteImport.update({
  id: '/api/guru/chat',
  path: '/api/guru/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTelegramRoute = ApiAuthTelegramRouteImport.update({
  id: '/api/auth/telegram',
  path: '/api/auth/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPracticeSendRemindersRoute =
  ApiPublicPracticeSendRemindersRouteImport.update({
    id: '/api/public/practice/send-reminders',
    path: '/api/public/practice/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/legal/$doc': typeof LegalDocRoute
  '/api/auth/telegram': typeof ApiAuthTelegramRoute
  '/api/guru/chat': typeof ApiGuruChatRoute
  '/api/public/practice/send-reminders': typeof ApiPublicPracticeSendRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/legal/$doc': typeof LegalDocRoute
  '/api/auth/telegram': typeof ApiAuthTelegramRoute
  '/api/guru/chat': typeof ApiGuruChatRoute
  '/api/public/practice/send-reminders': typeof ApiPublicPracticeSendRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/legal/$doc': typeof LegalDocRoute
  '/api/auth/telegram': typeof ApiAuthTelegramRoute
  '/api/guru/chat': typeof ApiGuruChatRoute
  '/api/public/practice/send-reminders': typeof ApiPublicPracticeSendRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/journal'
    | '/legal/$doc'
    | '/api/auth/telegram'
    | '/api/guru/chat'
    | '/api/public/practice/send-reminders'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/journal'
    | '/legal/$doc'
    | '/api/auth/telegram'
    | '/api/guru/chat'
    | '/api/public/practice/send-reminders'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/journal'
    | '/legal/$doc'
    | '/api/auth/telegram'
    | '/api/guru/chat'
    | '/api/public/practice/send-reminders'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  JournalRoute: typeof JournalRoute
  LegalDocRoute: typeof LegalDocRoute
  ApiAuthTelegramRoute: typeof ApiAuthTelegramRoute
  ApiGuruChatRoute: typeof ApiGuruChatRoute
  ApiPublicPracticeSendRemindersRoute: typeof ApiPublicPracticeSendRemindersRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guru/chat': {
      id: '/api/guru/chat'
      path: '/api/guru/chat'
      fullPath: '/api/guru/chat'
      preLoaderRoute: typeof ApiGuruChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/telegram': {
      id: '/api/auth/telegram'
      path: '/api/auth/telegram'
      fullPath: '/api/auth/telegram'
      preLoaderRoute: typeof ApiAuthTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/practice/send-reminders': {
      id: '/api/public/practice/send-reminders'
      path: '/api/public/practice/send-reminders'
      fullPath: '/api/public/practice/send-reminders'
      preLoaderRoute: typeof ApiPublicPracticeSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  JournalRoute: JournalRoute,
  LegalDocRoute: LegalDocRoute,
  ApiAuthTelegramRoute: ApiAuthTelegramRoute,
  ApiGuruChatRoute: ApiGuruChatRoute,
  ApiPublicPracticeSendRemindersRoute: ApiPublicPracticeSendRemindersRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
